### PR TITLE
Add gha

### PR DESCRIPTION
**Pull request by medewitt**
First step at infrastructure to build the pkgdown automatically on push. I still need to do some investigation on why the tests are failing on the linux boxes.

### CODE REVIEW

**Comment by seabbs** [comment]
Looks good. This GitHub Actions integration is nice. I think the tests fail due to the seed changing between runs and the model being tested (`bsts`) being quite prone to failing to fit data (and hence sometimes returns NAs). May be mistaken though.

**Comment by seabbs** [comment]
Going to merge as I think the tests failing is nothing to do with this PR.

**Comment by medewitt** [comment]
@seabbs whenever you can, you might need to go into repository settings and change from where github serves the website from "docs" to "gh-pages"

**Comment by seabbs** [comment]
Good point - forgot to do this. On it now.

**Comment by seabbs** [comment]
Done

**Pull request merged**
