### PR TITLE
Create plot_compare_timeseries

### PR DESCRIPTION
**Pull request by andreamrau**
This branch addresses [issue #54](https://github.com/epiforecasts/EpiSoon/issues/54) in *EpiSoon* to provide visualisation for the output of `compare_timeseries`.

- Create `plot_compare_timeseries` function (a wrapper that produces one or more of the summary plots, horizon score plot, and region score plot)
- Include (unexported) accessory plot functions
- Create related man page for `plot_compare_timeseries`
- Update NAMESPACE for new function export and needed imports from *cowplot* and *ggplot2*

These code updates are adapted from:
https://github.com/nikosbosse/covidevaluation/blob/master/R/evaluate_models.R

A few comments/notes:
- I replaced all calls to *patchwork* with *cowplot* to avoid adding another dependency
- I mostly left in place the tidyerse nonstandard evaluation, with the exception of a couple that caused warnings in the check
- I did not implement tests for this plotting function
- I did not (yet) include the `plot_case_rt_comparison` function in the code, as it relies on *EpiNow* output

### CODE REVIEW

**Comment by nikosbosse** [comment]
Nice, this looks really cool, thanks a lot!
One thing: I do get a warning for the horizon score plot when running the examples

```
plot_rt_horizon_score <-
      EpiSoon::summarise_scores(rt_scores, "horizon") %>%
      adjust_score("horizon") %>%
      make_horizon_score_plot(label = "Rt") + 
      ggplot2::theme(text = ggplot2::element_text(family = "Sans Serif"))
    
    plot_cases_horizon_score <-
      EpiSoon::summarise_scores(case_scores, "horizon") %>%
      adjust_score("horizon") %>%
      make_horizon_score_plot(label = "Cases")
```
the warning says: "Transformation introduced infinite values in continuous y-axis"

have you encountered the same issue?

**Comment by andreamrau** [comment]
I wasn't seeing this warning myself when I ran the `plot_compare_timeseries examples`, but it's just a warning to indicate that the log10 transformation applied to the y-axis of the horizon score plots was causing some NAs. To avoid having those warnings pop up, I just added a filter step to include only positive scores (with the exception of Bias) before plotting. That should take care of it, hopefully!

**Comment by seabbs** [comment]
This is great - thanks for this. Super useful. The one warning I see on the CI looks unrelated so merging.

**Comment by andreamrau** [comment]
Great, glad to hear!

**Comment by seabbs** [comment]
as an FYI we are using this both for our UK forecasts and US forecasts both of which get submitted tonight so very timely!

**Pull request merged**
